### ISSUE TITLE
Transferring IOS XE Image to multiple Access Switches

### ISSUE THREAD

**Issue by Tes3awy** [jerome-t/nxos-scp-upload#4]
To begin with, thanks a lot for this handy program. It's really helpful and saves a lot of time.

I just had one issue. I am trying to transfer `cat9k_lite_iosxe.17.03.03.SPA.bin` _(about 480MBs)_ to three C9200L-48P-4G access switches, but I got an error `socket.timeout()`. However, I was able to find the IOS image on the three switches flash and the images were verified!

I added `socket_timeout=200.0` to this [line](https://github.com/jerome-t/netmiko-scp-multi-thread-upload/blob/ec9349664503649a596c3508b090e6f8e578cb85/scp-multi-upload.py#L54) before running to prevent any timeouts but I still get one!

Any reason for why this is happening?

Thanks a lot!

**Comment by jerome-t** [comment]
Hi,

Thanks a lot for your comment.

It's difficult to see what is the issue here.
For debugging purposes, you may add a "catch-all" at line 73 to catch any exception and see more details.

Something like:
    except:
        print(“Error: ”, sys.exc_info()[0], “occurred.”)

I hope it helps.
Best,
Jerome

**Comment by Tes3awy** [comment]
Hello @jerome-t,

Today, I tried doing it again but raised the socket timeout to `250.0` and it worked for 6 access switches concurrently. It's all about the timeout. So for a `~500MBs` IOS image size, `socket_timeout=250.0` is perfect.

**Update:**

The IOS image transfer took exactly 00:14:28 to be transfered to all six switches on 1G link.
