### ISSUE TITLE
Problems with uploads

### ISSUE THREAD

**Issue by jgeromero** [jerome-t/nxos-scp-upload#5]
Hello -- I'm running a script to upload a TGZ image for Juniper EX3400 devices, the script runs and it says that it uploaded files but when I log into the device the files are missing from /var/tmp

```
Please, confirm the upload of junos-arm-32-20.4R3-S3.4.tgz on: 
10.100.1.1
10.100.1.2
10.100.1.3
10.100.1.4
10.100.1.5
10.100.1.6
10.100.1.7
10.100.1.8
10.100.1.9
10.100.1.10
10.100.1.11
10.100.1.12
Proceed? [n]|y: y
--------------------------------------------------------------------------------
Please insert your username: root
And your password
Password: 
--------------------------------------------------------------------------------
Upload on: 10.100.1.1
Upload on: 10.100.1.2
Upload on: 10.100.1.3
Upload on: 10.100.1.4
Upload on: 10.100.1.5
Upload on: 10.100.1.6
Upload on: 10.100.1.7
Upload on: 10.100.1.8
Upload on: 10.100.1.1
Upload on: 10.100.1.6
Upload on: 10.100.1.4
Upload on: 10.100.1.7
================================================================================
Uploads completed in 7.7323243618011475 seconds.
```

**Comment by jerome-t** [comment]
Hi,

Unfortunately, I have no Juniper device to test it. But, this script use mostly the SCP function of Netmiko described here:
https://pynet.twb-tech.com/blog/expanding-netmiko-secure-copy-support.html

Maybe you can try it with a single device, using this snippet of code below, to see if it works:
https://github.com/twin-bridges/pynet_articles/blob/main/netmiko_scp/test_file_transfer.py

If you have the same problem with a single device and the above script, it's probably an issue with your device/credentials/permissions, or anything similar. Or eventually with the Netmiko code itself. I'm not the author.

I let you check that first. Thank you.
Jerome

**Comment by jgeromero** [comment]
Hi @jerome-t, just reporting that it worked with a single device using test code linked.

**Comment by jgeromero** [comment]
Closing as I went another way for transfers. Thanks.
